geekshop/admins/urls.py
from django.urls import path
from admins.views import index,UserListView,ProductListView,CategoryListView,UserCreateView,ProductCreateView, \
    CategoryCreateView,UserUpdateView,CategoryDeleteView,CategoryUpdateView,UserDeleteView,ProductUpdateView, ProductDeleteView


app_name = 'admins'

urlpatterns = [
    path('', index, name='index'),
    path('users/', UserListView.as_view(), name='admin_users'),
    path('users-create/', UserCreateView.as_view(), name='admin_users_create'),
    path('users-update/<int:pk>', UserUpdateView.as_view(), name='admin_users_update'),
    path('users-delete/<int:pk>', UserDeleteView.as_view(), name='admin_users_delete'),
    path('products/', ProductListView.as_view(), name='admin_products'),
    path('products-create/', ProductCreateView.as_view(), name='admin_products_create'),
    path('products-update/<int:pk>', ProductUpdateView.as_view(), name='admin_products_update'),
    path('products-delete/<int:pk>', ProductDeleteView.as_view(), name='admin_products_delete'),
    path('categories/', CategoryListView.as_view(), name='admin_categories'),
    path('categories-create/', CategoryCreateView.as_view(), name='admin_categories_create'),
    path('categories-update/<int:pk>', CategoryUpdateView.as_view(), name='admin_categories_update'),
    path('categories-delete/<int:pk>', CategoryDeleteView.as_view(), name='admin_categories_delete'),


]

geekshop/admins/models.py
from django.db import models

# Create your models here.

geekshop/admins/forms.py
from authapp.forms import UserRegisterForm
from django import forms
from authapp.models import User
from authapp.forms import UserProfileForm
from django.forms import ModelForm
from mainapp.models import Product, ProductCategory


class UserAdminRegisterForm(UserRegisterForm):
    image = forms.ImageField(widget=forms.FileInput(),required=False)

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'image', 'age', 'password1', 'password2')

    def __init__(self, *args, **kwargs):
        super(UserAdminRegisterForm, self).__init__(*args, **kwargs)

        for _, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control py-4'
        self.fields['image'].widget.attrs['class'] = 'custom-file-input'


class UserAdminProfileForm(UserProfileForm):
    email = forms.EmailField(widget=forms.EmailInput())
    username = forms.CharField(widget=forms.TextInput())

    def __init__(self, *args, **kwargs):
        super(UserAdminProfileForm, self).__init__(*args, **kwargs)

        self.fields['username'].widget.attrs['readonly'] = False
        self.fields['email'].widget.attrs['readonly'] = False
        for _, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control py-4'
        self.fields['image'].widget.attrs['class'] = 'custom-file-input'


class ProductAdminForm(ModelForm):

    class Meta:
        model = Product
        fields = ('name', 'description', 'price', 'quantity', 'category', 'image')

    def __init__(self, *args, **kwargs):
        super(ProductAdminForm, self).__init__(*args, **kwargs)
        self.fields['name'].widget.attrs['placeholder'] = 'Введите название продукта'
        self.fields['description'].widget.attrs['placeholder'] = 'Введите описание продукта'
        self.fields['quantity'].widget.attrs['placeholder'] = 'Введите количество товара на складе'
        self.fields['price'].widget.attrs['placeholder'] = 'Введите цену'
        self.fields['category'].widget.attrs['placeholder'] = 'Выберите категорию'

        for _, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control py-4'
        self.fields['image'].widget.attrs['class'] = 'custom-file-input'
        self.fields['category'].widget.attrs['class'] = 'related-widget-wrapper'


class CategoryAdminForm(ModelForm):

    class Meta:
        model = ProductCategory
        fields = ('name', 'description')

    def __init__(self, *args, **kwargs):
        super(CategoryAdminForm, self).__init__(*args, **kwargs)
        for _, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control py-4'

geekshop/admins/views.py
from django.contrib.auth.decorators import user_passes_test
from django.http import HttpResponseRedirect
from django.shortcuts import render
from authapp.models import User
from admins.forms import UserAdminRegisterForm, UserAdminProfileForm
from django.urls import reverse, reverse_lazy
from mainapp.models import Product,ProductCategory
from admins.forms import ProductAdminForm,CategoryAdminForm
from django.views.generic import ListView, CreateView,UpdateView,DeleteView,DetailView,TemplateView
from mainapp.mixin import BaseClassContextMixin, UserDispatchMixin



@user_passes_test(lambda u: u.is_superuser)
def index(request):
    return render(request, 'admins/admin.html')



class UserListView(ListView, BaseClassContextMixin, UserDispatchMixin):
    model = User
    template_name = 'admins/admins-users-read.html'
    title = 'Админка | Пользователи'


class UserCreateView(CreateView, BaseClassContextMixin, UserDispatchMixin):
    model = User
    template_name = 'admins/admins-users-create.html'
    form_class = UserAdminRegisterForm
    title = 'Админка | Пользователи'
    success_url = reverse_lazy('admins:admin_users')



class UserUpdateView(UpdateView, BaseClassContextMixin, UserDispatchMixin):
    model = User
    template_name = 'admins/admins-users-update-delete.html'
    form_class = UserAdminProfileForm
    title = 'Админка | Редактирование пользователя'
    success_url = reverse_lazy('admins:admin_users')


class UserDeleteView(DeleteView, UserDispatchMixin):
    model = User
    template_name = 'admins/admins-users-update-delete.html'
    form_class = UserAdminProfileForm
    success_url = reverse_lazy('admins:admin_users')

    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        success_url = self.get_success_url()
        self.object.is_active = not self.object.is_active
        self.object.save()
        return HttpResponseRedirect(success_url)

class ProductListView(ListView, BaseClassContextMixin, UserDispatchMixin):
    model = Product
    template_name = 'admins/admin-products-read.html'
    title = 'Админка | Товары'


class ProductCreateView(CreateView, BaseClassContextMixin, UserDispatchMixin):
    model = Product
    template_name = 'admins/admin-products-create.html'
    form_class = ProductAdminForm
    title = 'Админка | Новый товар'
    success_url = reverse_lazy('admins:admin_products')


class ProductUpdateView(UpdateView, BaseClassContextMixin, UserDispatchMixin):
    model = Product
    template_name = 'admins/admin-products-update-delete.html'
    form_class = ProductAdminForm
    title = 'Админка | Редактирование товара'
    success_url = reverse_lazy('admins:admin_products')


class ProductDeleteView(DeleteView, UserDispatchMixin):
    model = Product
    template_name = 'admins/admin-products-update-delete.html'
    form_class = ProductAdminForm
    success_url = reverse_lazy('admins:admin_products')




class CategoryListView(ListView, BaseClassContextMixin, UserDispatchMixin):
    model = ProductCategory
    template_name = 'admins/admin-categories-read.html'
    title = 'Админка | Категории'


class CategoryCreateView(CreateView, BaseClassContextMixin, UserDispatchMixin):
    model = ProductCategory
    template_name = 'admins/admin-categories-create.html'
    form_class = CategoryAdminForm
    title = 'Админка | Новая категория'
    success_url = reverse_lazy('admins:admin_categories')


class CategoryUpdateView(UpdateView, BaseClassContextMixin, UserDispatchMixin):
    model = ProductCategory
    template_name = 'admins/admin-categories-update-delete.html'
    form_class = CategoryAdminForm
    title = 'Админка | Редактирование категории'
    success_url = reverse_lazy('admins:admin_categories')



class CategoryDeleteView(DeleteView, UserDispatchMixin):
    model = ProductCategory
    template_name = 'admins/admin-categories-update-delete.html'
    form_class = CategoryAdminForm
    success_url = reverse_lazy('admins:admin_categories')

geekshop/admins/templates/admins/admin-categories-read.html
{% extends 'admins/base.html' %}

{% block content %}
    <div id="layoutSidenav_content">
        <main>
            <div class="container-fluid">
                <h1 class="mt-4">Категории</h1>
                <div class="card mb-4">
                    <div class="card-header">
                        <i class="fas fa-table mr-1"></i>
                        Категории
                    </div>
                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                                <thead>
                                <tr>
                                    <th>Наименование категории</th>
                                    <th>Описание</th>
                                </tr>
                                </thead>
                                <tfoot>
                                <tr>
                                    <th>Наименование категории</th>
                                    <th>Описание</th>
                                </tr>
                                </tfoot>
                                <tbody>
                                {% for category in object_list %}
                                    <tr>
                                        <td><a href="{% url 'admins:admin_categories_update' category.id %}" style="color: dodgerblue">{{category.name}}</td>
                                        <td>{{category.description}}</td>
                                    </tr>
                                {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                    <div class="card-footer">
                        <a href="{% url 'admins:admin_categories_create' %}">
                            <button class="btn btn-success">Создать категорию</button>
                        </a>
                    </div>
                </div>
            </div>
        </main>
        <footer class="py-4 bg-light mt-auto">
            <div class="container-fluid">
                <div class="d-flex align-items-center justify-content-between small">
                    <div class="text-muted">Copyright &copy; GeekShop 2021</div>
                </div>
            </div>
        </footer>
    </div>
{% endblock %}

geekshop/admins/templates/admins/admin-categories-update-delete.html
{% extends 'admins/base.html' %}

{% block content%}
    <div id="layoutSidenav_content">
        <main>
            {% if form.errors %}
                <div class="alert alert-warning alert-dismissible fade show" role="alert" style="margin-top: 50px;">
                    {% for field, error in form.errors.items %}
                        {{ error | escape }}
                    {% endfor %}

                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                    </button>
                </div>
            {% endif %}
            <div class="container-fluid">
                <h1 class="mt-4">Редактирование категории | {{productcategory.name}}</h1>
                <div class="card-body">
                    <form action="{% url 'admins:admin_categories_update' productcategory.id %}" method="post" >
                        {% csrf_token %}
                        <div class="form-row">
                            <div class="col-lg-6">
                                <div class="form-group">
                                    <label class="small mb-1" for="{{form.name.id_for_label}}">Название</label>
                                    {{form.name}}
                                </div>
                            </div>
                            <div class="col-lg-6">
                                <div class="form-group">
                                    <label class="small mb-1" for="{{form.description.id_for_label}}">Описание категории</label>
                                    {{form.description}}
                                </div>
                            </div>
                        </div>

                        <div class="form-row">
                            <div class="col-lg-12" style="margin-top: 33px;">
                                <input class="btn btn-info btn-block" type="submit" value="Сохранить">
                            </div>
                        </div>
                    </form>
                    <form action="{% url 'admins:admin_categories_delete' productcategory.id %}" method="post">
                        {% csrf_token %}
                        <div class="row">
                            <div class="col-lg-12" style="margin-top: 33px;">
                                <input class="btn btn-danger btn-block" type="submit" value="Удалить">
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </main>
        <footer class="py-4 bg-light mt-auto">
            <div class="container-fluid">
                <div class="d-flex align-items-center justify-content-between small">
                    <div class="text-muted">Copyright &copy; GeekShop 2021</div>
                </div>
            </div>
        </footer>
    </div>
{% endblock %}

geekshop/admins/templates/admins/admin-products-read.html
{% extends 'admins/base.html' %}

{% block content %}
    <div id="layoutSidenav_content">
        <main>
            <div class="container-fluid">
                <h1 class="mt-4">Товары</h1>
                <div class="card mb-4">
                    <div class="card-header">
                        <i class="fas fa-table mr-1"></i>
                        Товары
                    </div>
                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                                <thead>
                                <tr>
                                    <th>Наименование товара</th>
                                    <th>Категория</th>
                                    <th>Описание</th>
                                    <th>Цена</th>
                                    <th>Количество</th>
                                    <th>Картинка</th>
                                </tr>
                                </thead>
                                <tfoot>
                                <tr>
                                    <th>Наименование товара</th>
                                    <th>Категория</th>
                                    <th>Описание</th>
                                    <th>Цена</th>
                                    <th>Количество</th>
                                    <th>Картинка</th>
                                </tr>
                                </tfoot>
                                <tbody>
                                {% for product in object_list %}
                                    <tr>
                                        <td><a href="{% url 'admins:admin_products_update' product.id %}" style="color: dodgerblue">{{product.name}}</a></td>

                                        <td>{{product.category}}</td>
                                        <td>{{product.description}}</td>
                                        <td>{{product.price}}</td>
                                        <td>{{product.quantity}}</td>
                                        <td><img {% if product.image %} src="{{product.image.url}}" {%endif%} width="50" height="50" /></td>
                                    </tr>
                                {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                    <div class="card-footer">
                        <a href="{% url 'admins:admin_products_create' %}">
                            <button class="btn btn-success">Создать товар</button>
                        </a>
                    </div>
                </div>
            </div>
        </main>
        <footer class="py-4 bg-light mt-auto">
            <div class="container-fluid">
                <div class="d-flex align-items-center justify-content-between small">
                    <div class="text-muted">Copyright &copy; GeekShop 2021</div>
                </div>
            </div>
        </footer>
    </div>
{% endblock %}

geekshop/admins/templates/admins/admin-products-update-delete.html
{% extends 'admins/base.html' %}

{% block content%}
    <div id="layoutSidenav_content">
        <main>
            {% if form.errors %}
                <div class="alert alert-warning alert-dismissible fade show" role="alert" style="margin-top: 50px;">
                    {% for field, error in form.errors.items %}
                        {{ error | escape }}
                    {% endfor %}

                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                    </button>
                </div>
            {% endif %}
            <div class="container-fluid">
                <h1 class="mt-4">Редактирование товара | {{product.name}}</h1>
                <div class="card-body">
                    <form action="{% url 'admins:admin_products_update' product.id %}" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="form-row">
                            <div class="col-lg-6">
                                <div class="form-group">
                                    <label class="small mb-1" for={{form.name.id_for_label}}>Название</label>
                                    {{form.name}}
                                </div>
                            </div>
                            <div class="col-lg-6">
                                <div class="form-group">
                                    <label class="small mb-1" for="{{form.category.id_for_label}}">Категория</label>
                                    {{form.category}}
                                </div>
                            </div>
                        </div>
                        <div class="form-row mb-2">
                            <div class="col-lg-12">
                                <div class="custom-file">
                                    {{ form.image}}
                                    <label class="custom-file-label" for="{{ form.image.id_for_label }}">Выберите изображение</label>
                                </div>
                            </div>
                        </div>
                        <div class="form-row">
                            <div class="col-lg-6">
                                <label class="small mb-1" for="{{form.price.id_for_label}}">Цена</label>
                                {{form.price}}
                            </div>
                            <div class="col-lg-6">
                                <label class="small mb-1" for="{{form.quantity.id_for_label}}">Количество на складе</label>
                                {{form.quantity}}
                            </div>
                        </div>
                        <div>
                            <div class="col-lg-12">
                                <label class="small mb-1" for=" {{ form.description.id_for_label }}">Описание</label>
                                {{ form.description }}
                        </div>
                        </div>
                        <div class="form-row">
                            <div class="col-lg-12" style="margin-top: 33px;">
                                <input class="btn btn-info btn-block" type="submit" value="Сохранить">
                            </div>
                        </div>
                    </form>
                    <form action="{% url 'admins:admin_products_delete' product.id %}" method="post">
                        {% csrf_token %}
                        <div class="row">
                            <div class="col-lg-12" style="margin-top: 33px;">
                                <input class="btn btn-danger btn-block" type="submit" value="Удалить">
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </main>
        <footer class="py-4 bg-light mt-auto">
            <div class="container-fluid">
                <div class="d-flex align-items-center justify-content-between small">
                    <div class="text-muted">Copyright &copy; GeekShop 2021</div>
                </div>
            </div>
        </footer>
    </div>
{% endblock %}

geekshop/admins/templates/admins/admin.html
{% extends 'admins/base.html' %}

{% block content %}
    <div id="layoutSidenav_content">
        <main>
            <div class="container-fluid">
                <h1 class="mt-4">Административная панель</h1>

            </div>
        </main>
        <footer class="py-4 bg-light mt-auto">
            <div class="container-fluid">
                <div class="d-flex align-items-center justify-content-between small">
                    <div class="text-muted">Copyright &copy; GeekShop 2021</div>
                </div>
            </div>
        </footer>
    </div>

{% endblock %}

geekshop/admins/templates/admins/admins-users-read.html
{% extends 'admins/base.html' %}

{% block content %}
    <div id="layoutSidenav_content">
        <main>
            <div class="container-fluid">
                <h1 class="mt-4">Пользователи</h1>
                <div class="card mb-4">
                    <div class="card-header">
                        <i class="fas fa-table mr-1"></i>
                        Пользователи
                    </div>
                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                                <thead>
                                <tr>
                                    <th>Имя пользователя</th>
                                    <th>Имя</th>
                                    <th>Фамилия</th>
                                    <th>Адрес эл. почты</th>
                                    <th>Персонал сайта</th>
                                    <th>Активный</th>
                                </tr>
                                </thead>
                                <tfoot>
                                <tr>
                                    <th>Имя пользователя</th>
                                    <th>Имя</th>
                                    <th>Фамилия</th>
                                    <th>Адрес эл. почты</th>
                                    <th>Персонал сайта</th>
                                    <th>Активный</th>
                                </tr>
                                </tfoot>
                                <tbody>
                                {% for user in object_list %}
                                    <tr {% if user.is_active %} bgcolor="#EEF0EE" {% endif %}>

                                        <td><a href="{% url 'admins:admin_users_update' user.id %}" style="color: dodgerblue">{{user.username}}</a></td>
                                        <td>{{user.first_name}}</td>
                                        <td>{{user.last_name}}</td>
                                        <td>{{user.email}}</td>
                                        <td class="text-center">
                                                {% if user.is_staff %}
                                                    <i class="fas fa-check-circle"></i>
                                                {% else %}
                                                    <i class="fas fa-times-circle"></i>
                                                {% endif %}
                                        </td>
                                        <td class="text-center">
                                            {% if user.is_active %}
                                                    <i class="fas fa-check-circle" style="color:red">

                                                    </i>
                                                {% else %}
                                                    <i class="fas fa-times-circle"></i>
                                                {% endif %}
                                        </td>
                                    </tr>
                                {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                    <div class="card-footer">
                        <a href="{% url 'admins:admin_users_create' %}">
                            <button class="btn btn-success">Создать пользователя</button>
                        </a>
                    </div>
                </div>
            </div>
        </main>
        <footer class="py-4 bg-light mt-auto">
            <div class="container-fluid">
                <div class="d-flex align-items-center justify-content-between small">
                    <div class="text-muted">Copyright &copy; GeekShop 2021</div>
                </div>
            </div>
        </footer>
    </div>
{% endblock %}

geekshop/admins/templates/admins/admins-users-update-delete.html
{% extends 'admins/base.html' %}

{% block content%}
    <div id="layoutSidenav_content">
        <main>
            {% if form.errors %}
                <div class="alert alert-warning alert-dismissible fade show" role="alert" style="margin-top: 50px;">
                    {% for field, error in form.errors.items %}
                        {{ error | escape }}
                    {% endfor %}

                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                    </button>
                </div>
            {% endif %}
            <div class="container-fluid">
                <h1 class="mt-4">Редактирование пользователя | {{user.username}}</h1>
                <div class="card-body">
                    <form action="{% url 'admins:admin_users_update' user.id %}" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="form-row">
                            <div class="col-lg-6">
                                <div class="form-group">
                                    <label class="small mb-1" for="{{form.first_name.id_for_label}}">Имя</label>
                                    {{form.first_name}}
                                </div>
                            </div>
                            <div class="col-lg-6">
                                <div class="form-group">
                                    <label class="small mb-1" for="{{form.last_name.id_for_label}}">Фамилия</label>
                                    {{form.last_name}}
                                </div>
                            </div>
                        </div>
                        <div class="form-row mb-2">
                            <div class="col-lg-12">
                                <div class="custom-file">
                                    {{ form.image}}
                                    <label class="custom-file-label" for="{{ form.image.id_for_label }}">Выберите изображение</label>
                                </div>
                            </div>
                        </div>
                        <div class="form-row">
                            <div class="col-lg-6">
                                <label class="small mb-1" for="{{form.username.id_for_label}}">Имя пользователя</label>
                                {{form.username}}
                            </div>
                            <div class="col-lg-6">
                                <label class="small mb-1" for="{{form.email.id_for_label}}">Адрес электронной
                                    почты</label>
                                {{form.email}}
                            </div>
                        </div>
                        <div>
                            <div class="col-lg-2">
                                <label class="small mb-1" for="{{ form.age.id_for_label }}">Возраст</label>
                                {{ form.age }}
                        </div>
                        </div>
                        <div class="form-row">
                            <div class="col-lg-12" style="margin-top: 33px;">
                                <input class="btn btn-info btn-block" type="submit" value="Сохранить">
                            </div>
                        </div>
                    </form>
                    <form action="{% url 'admins:admin_users_delete' user.id %}" method="post">
                        {% csrf_token %}
                        <div class="row">
                            <div class="col-lg-12" style="margin-top: 33px;">
                                <input class="btn btn-danger btn-block" type="submit" value="Удалить">
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </main>
        <footer class="py-4 bg-light mt-auto">
            <div class="container-fluid">
                <div class="d-flex align-items-center justify-content-between small">
                    <div class="text-muted">Copyright &copy; GeekShop 2021</div>
                </div>
            </div>
        </footer>
    </div>
{% endblock %}

geekshop/admins/templates/admins/includes/siberia_bar.html
 <div id="layoutSidenav_nav">
        <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
            <div class="sb-sidenav-menu">
                <div class="nav">
                    <div class="sb-sidenav-menu-heading">Приложения</div>
                    <a class="nav-link" href="{% url 'admins:admin_users' %}">
                        <div class="sb-nav-link-icon">
                            <i class="fas fa-users"></i>
                        </div>
                        Пользователи
                    </a>
                    <a class="nav-link" href="{% url 'admins:admin_categories' %}">
                        <div class="sb-nav-link-icon">
                            <i class="fas fa-shopping-basket"></i>
                        </div>
                        Категории
                    </a>
                    <a class="nav-link" href="{% url 'admins:admin_products' %}">
                        <div class="sb-nav-link-icon">
                            <i class="fas fa-tshirt"></i>
                        </div>
                        Продукты
                    </a>
                </div>
            </div>
            <div class="sb-sidenav-footer"></div>
        </nav>
 </div>