geekshop/mainapp/urls.py
from django.urls import path
from mainapp.views import products, details


app_name = 'mainapp'

urlpatterns = [
    path('', products, name='products'),
    path('details/<int:product_id>', details, name='details'),
    path('category/<int:id_category>/<int:page>', products, name='category'),

]

geekshop/mainapp/models.py
from django.db import models

# Create your models here.
class ProductCategory(models.Model):
    name = models.CharField(max_length=64)
    description = models.TextField(blank=True, null=True)


    def __str__(self):
        return f'{self.name}'




class Product(models.Model):
    name = models.CharField(max_length=128)
    image = models.ImageField(upload_to='product_image', blank=True)
    price = models.DecimalField(max_digits=8, decimal_places=2)
    description = models.TextField(blank=True, null=True)
    quantity = models.PositiveIntegerField(default=0)
    category = models.ForeignKey(ProductCategory, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.name}|{self.category}'

geekshop/mainapp/views.py
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.shortcuts import render
from .models import ProductCategory, Product


def index(request):
    context = {
        'title': "geeekshop"}
    return render(request, 'mainapp/index.html', context)


def products(request, id_category=0,page=1):
    context = {
        'title' : "каталог",
        'header': 'добро пожаловать на сайт',
        'user'  : request.user,
        'range' : [1,2,3],
        'category': id_category
    }

    if id_category: # если 0, то идем в else и выводим все продукты
        products = Product.objects.filter(category_id=id_category)
    else:
        products = Product.objects.all()


    p = Paginator(products, 3)
    categories = ProductCategory.objects.all()
    context['categories'] = categories

    try:
        products_paginator = p.page(page)
    except PageNotAnInteger:
        products_paginator = p.page(1)
    except EmptyPage:
        products_paginator = p.page(p.num_pages)

    context['products'] = products_paginator

    return render(request, 'mainapp/products.html', context)


def details(request, product_id):
    context = {
        'title' : "Geekshop",
        'user'  : request.user
    }

    context['product'] = Product.objects.get(id=product_id)

    return render(request, 'mainapp/details.html', context)

geekshop/mainapp/templates/mainapp/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>{{ title|title }}</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css'%}" rel="stylesheet">

    {% block css %}}

    {% endblock %}
</head>

<body>

<!-- Navigation -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container">
        <a class="navbar-brand" href="{% url 'index' %}">GeekShop {% now "jS F Y" %}</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive"
                aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'mainapp:products' %}">Каталог<i class="fas fa-shopping-bag"></i> </a>
                </li>
                {% if not user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'authapp:login'%}">Войти <i class="fas fa-sign-in-alt"></i></a>
                </li>
                {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'authapp:profile'%}">{{ user.username}}
                        <i class="fas fa-user-circle"></i>
                    </a>
                </li>
                {% if user.is_superuser %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'admins:index' %}">
                            <i class="fas fa-users-cog">admin</i>
                        </a>
                    </li>
                {% endif %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'authapp:logout' %}">Выйти <i class="fas fa-sign-out-alt"></i></a>
                </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

{% block content %}
{% endblock %}

{% block footer %}
{% endblock%}
<!-- Bootstrap core JavaScript -->
<script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
<script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<script src="{% static 'js/basket.js' %}"></script>


<!-- FontAwesome script -->
<script src="{% static 'vendor/fontawesome/fontawesome-icons.js' %}" crossorigin="anonymous"></script>

</body>

</html>

geekshop/mainapp/templates/mainapp/details.html
    {% extends 'mainapp/base.html' %}
    {% load static %}

    {% block css %}
        <link href="{% static 'css/products.css' %}" rel="stylesheet">
    {% endblock %}

    {% block content %}
        <div class="container">
            <div class="row">
                <div class="col-lg-3">
                    <h1 class="my-4">GeekShop</h1>
                    <div class="list-group">
                        <a href="{% url 'mainapp:products' %}" class="list-group-item">Назад</a>
                    </div>
                </div>

                <div class="col-lg-9">
                    <div class="row my-5">
                        <div class="card" style="width: 20rem;">
                            <img src="/media/{{product.image}}" class="card-img-top" alt="...">
                            <div class="card-body">
                                <h5 class="card-title">{{ product.name }}</h5>
                                <p class="card-text">{{ product.description }}</p>
                            </div>
                            <ul class="list-group list-group-flush">
                                <li class="list-group-item">{{ product.price }} руб</li>
                                <li class="list-group-item">В наличии: {{ product.quantity }}</li>
                            </ul>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    {% endblock %}

    {% block footer %}
         {% include 'mainapp/footer.html' %}
    {% endblock %}

geekshop/mainapp/templates/mainapp/footer.html
<footer class="py-5 bg-dark">
    <div class="container">
        <p class="m-0 text-center text-white">Copyright &copy; GeekShop 2021</p>
    </div>
</footer>

geekshop/mainapp/templates/mainapp/index.html
{% extends "mainapp/base.html" %}
{% load static %}

{% block css %}
<link href="{% static 'css/index.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}
<section>
    <div class="container">
        <div class="row">
            <div class="col-lg-6">
                <h1 class="mt-5">GeekShop Store</h1>
                <p>
                    Новые образы и лучшие бренды на GeekShop Store.
                    Бесплатная доставка по всему миру! Аутлет: до -70% Собственный бренд. -20% новым покупателям.
                </p>
                <button id="start-purchase-btn" type="button" class="btn btn-lg">
                    <a id="start-purchase-link" href="{% url 'mainapp:products' %}">
                        Начать покупки
                    </a>
                </button>
            </div>
        </div>
    </div>
</section>

{% endblock %}

geekshop/mainapp/templates/mainapp/products.html
{% extends 'mainapp/base.html' %}
{% load static %}

    {% block css %}
    <link href="{% static 'css/products.css' %}" rel="stylesheet">
    {% endblock %}
{% block content %}
<!-- Page Content -->
<div class="container">

    <div class="row">

        <div class="col-lg-3">

            <h1 class="my-4">GeekShop</h1>
            <div class="list-group">
                <a href="{% url 'mainapp:products'%}" class="list-group-item">Все категории</a>

                {% for categ in categories %}
                <a href="{% url 'mainapp:category' categ.id 1 %}" class="list-group-item">{{categ.name}}</a>
                {% endfor %}


            </div>

        </div>
        <!-- /.col-lg-3 -->

        <div class="col-lg-9">

            <div id="carouselExampleIndicators" class="carousel slide my-4" data-ride="carousel">
                <ol class="carousel-indicators">
                    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
                    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
                    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
                </ol>
                <div class="carousel-inner" role="listbox">
                    <div class="carousel-item active">
                        <img class="d-block img-fluid" src="{% static 'vendor/img/slides/slide-1.jpg' %}" alt="First slide">
                    </div>
                    <div class="carousel-item">
                        <img class="d-block img-fluid" src="{% static 'vendor/img/slides/slide-2.jpg' %}" alt="Second slide">
                    </div>
                    <div class="carousel-item">
                        <img class="d-block img-fluid" src="{% static 'vendor/img/slides/slide-3.jpg' %}" alt="Third slide">
                    </div>
                </div>
                <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="sr-only">Previous</span>
                </a>
                <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="sr-only">Next</span>
                </a>
            </div>

            <div class="row">
                {% for prod in products %}
                        <div class="col-lg-4 col-md-6 mb-4">
                            <div class="card h-100">
                                <a href="#"> <img class="card-img-top" src="{{prod.image.url}}" alt="">
                                </a>
                                <div class="card-body">
                                    <h4 class="card-title">
                                        <a href="{% url 'mainapp:details' prod.id %}" >{{prod.name}}</a>
                                    </h4>
                                    <h5>{{prod.price}} руб.</h5>
                                    <p class="card-text">{{prod.description}}</p>
                                </div>
                                <div class="card-footer text-center">
                                    <a href="{% url 'baskets:basket_add' prod.id %}" type="button" class="btn btn-outline-success">Отправить в корзину</a>
                                </div>
                            </div>
                        </div>
                {% endfor%}

            </div>

            <nav aria-label="Page navigation example">
                <ul class="pagination justify-content-center">
                    <li class="page-item ">
                        {% if products.has_previous %}
                            <a class="page-link" href="{% url 'mainapp:category' category products.previous_page_number %} " tabindex="-1" >Previous</a>
                        {% endif %}
                    </li>

                    {% for p in products.paginator.page_range %}
                        <li class="page-item">
                        <a class="page-link" href="{% url 'mainapp:category' category p %}" >{{p}}</a>
                        </li>
                    {% endfor %}

                    {% if products.has_next %}
                        <li class="page-item">
                            <a class="page-link" href="{% url 'mainapp:category' category products.next_page_number %}">Next</a>

                        </li>
                    {% endif %}
                </ul>
            </nav>

        </div>

    </div>

</div>
<!-- /.container -->
{% endblock%}
{% block footer %}
    {% include 'mainapp/footer.html' %}
{% endblock%}

<!-- Bootstrap core JavaScript -->
<script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
<script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

<!-- FontAwesome script -->
<script src="{% static 'vendor/fontawesome/fontawesome-icons.js' %}" crossorigin="anonymous"></script>

</body>

</html>